### PR TITLE
Fix various typos

### PR DESCRIPTION
**Pull request by HexDecimal**
I took a sweep through the sources and text files with a spell checker.

I fixed several, but due to the nature of the sources there are many that I can't fix easily without risking save compatibility.

The heavy use of `global` and scoped imports makes refactoring the source more difficult. I'll need that resolved before I can fix the spelling of variables and functions.

I can't test this at the moment, since the master branch is broken for me:
```
  File "...\src\itemFolder\story\__init__.py", line 12, in <module>
    import src.itemFolder.story.glassStatue
ModuleNotFoundError: No module named 'src.itemFolder.story.glassStatue'
```
I assume you forgot to track this module in Git.

After the master branch is fixed then I can test this. After that you should review my changes in case I made any mistakes.

You may also want a code spell-checking plugin for your IDE.

Is `Ghul` correct? It's not `Ghoul`?

### CODE REVIEW

**Comment by MarxMustermann** [comment]
i fixed the error, that was a botched merge from my side.

**Comment by MarxMustermann** [comment]
Yes. Ghul should be spelled Ghoul.

**Comment by MarxMustermann** [comment]
For now you can ignore save compatibility. To be honest there is no user that would complain right now.

**Comment by HexDecimal** [comment]
> For now you can ignore save compatibility.

I guess this is still in a very early state. I'll keep that in mind.

**Comment by MarxMustermann** [comment]
I'm checking your commit right now and did check your previous ones. I'll let you know when i'm done

**Comment by HexDecimal** [comment]
I already marked the PR as ready, so you can merge when finished.  The last change was a rebase onto master after your fixes were pushed.

**Comment by MarxMustermann** [comment]
thanks. It is merged now. Sorry for the mess.

The game is indeed in an early stage in the sense that i currently try to onboard some players and it has no real player base, yet. That is mostly, because the content was inaccessible for the most time. On the other hand i did sink 6 years into it so a lot of things are there. Sadly it also accumulated things there i should just delete.

The save states are one of those things, really. I switched to just pickling the state, because the explicit saving system just kept on breaking. I'll go through the code now and remove the remnants of the old system, so that is stops being confusing.

**Comment by MarxMustermann** [comment]
i also will see to the spell checking plugin

**Pull request merged**
